service: express-nodejs-typescript-serverless-scaffold
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
plugins:
  - serverless-offline